version: '2'  
services:  
  nginx:
    image: nginx:1.10.3
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./mcroblog_front_end/nginx/conf.d:/etc/nginx/conf.d
      - ./mcroblog_front_end/nginx/www.catchcat.cat:/etc/letsencrypt/live/www.catchcat.top
      - ./mcroblog_front_end/dist:/usr/src/app/mcroblog_front_end/dist
      - ./mcroblog_back_end/logs:/usr/src/app/mcroblog_back_end/logs
      - ./mcroblog_back_end/media:/usr/src/app/mcroblog_back_end/media
    depends_on:
      - web

  web:
    build: ./mcroblog_back_end
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && bash gunicorn_start.sh"
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: mysql:5.7.17
    container_name: sql01
    volumes:
      - ./mysql_database/mcroblog:/var/lib/mysql/mcroblog
    environment:
      - MYSQL_DATABASE=mcroblog
      - MYSQL_ROOT_PASSWORD=root  

