# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userextend_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='bane',
            field=models.CharField(default='c', max_length=10),
        ),
    ]
