# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userextend_bane'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='background_color',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextend',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='head_image',
            field=models.ImageField(default='head_img/default.png', upload_to='head_img/'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='profile',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='userextend',
            name='u_title',
            field=models.CharField(default='Untitled', max_length=20),
        ),
    ]
