# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170118_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserExtend'),
        ),
    ]
