# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170121_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
