# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_follow_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userextend',
            name='like_count',
            field=models.ImageField(default=0, upload_to=b''),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'blog')]),
        ),
    ]
