# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170216_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='follow_count',
            field=models.ImageField(default=0, upload_to=b''),
        ),
    ]
