# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userextend_follow_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='follow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
