# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userextend_latest_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='follow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
