# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='note',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
