# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170216_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
