# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20170118_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='HeadImage',
        ),
    ]
